model:
  type: 'fsq'
  input_dim: 768
  d_model: 128
  nhead: 8
  num_encoder_layers: 1
  num_decoder_layers: 1
  dim_feedforward: 384
  dropout: 0.1

training:
  batch_size: 32
  epochs: 5000
  print_epoch: 100
  learning_rate: 0.001
  alpha: 1.0
  verbose: True

paths:
  data: '../data/ioi3/ioi_resid_heads_last_pos.pt'
  model_save: '../models/'