model:
  type: 'vq'
  input_dim: 768
  d_model: 128
  nhead: 8
  num_encoder_layers: 1
  num_decoder_layers: 1
  dim_feedforward: 384
  dropout: 0.1
  codebook_size: 128
  codebook_dim: 16
  threshold_ema_dead_code: 2

training:
  batch_size: 32
  epochs: 2500
  print_epoch: 100
  learning_rate: 0.001
  alpha: 0.5
  verbose: True

paths:
  data: '../data/ioi3/ioi_resid_heads_last_pos.pt'
  model_save: '../models/'